In [ ]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
#We will be using Keras IMDB dataset. vocabulary size is a parameter 
#that is used the get data containing the given number of most occurring words in the entire corpus of textual data. 
from tensorflow.keras.layers import SimpleRNN, LSTM, GRU, Bidirectional, Dense, Embedding
from tensorflow.keras.models import Sequential
import numpy as np
from tensorflow.keras.layers import Dropout

In [34]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import SimpleRNN, LSTM, GRU, Bidirectional, Dense, Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dropout
# Đọc dữ liệu từ file CSV
data = pd.read_csv('C:/Users/hai/hai_data_dxl/News050523_hai.csv')

# Tiền xử lý dữ liệu nếu cần
# ...

embd_len = 32
max_words = 500
vocab_size = 5000

# Chuyển đổi dữ liệu đầu vào thành một tensor hoặc đối tượng có cấu trúc tương tự
input_data = np.array(data['new_content'])

tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(input_data)

# Chuyển đổi văn bản thành chỉ số
sequences = tokenizer.texts_to_sequences(input_data)

# Đảm bảo độ dài cố định của mỗi mẫu
padded_sequences = pad_sequences(sequences, maxlen=max_words)

input_tensor = tf.convert_to_tensor(padded_sequences)

# Creating a RNN model
RNN_model = Sequential(name="SimpleRNN")
RNN_model.add(Embedding(vocab_size,
						embd_len,
						input_length=max_words))

# In case of a stacked(more than one layer of RNN)
# use return_sequences=True
RNN_model.add(SimpleRNN(128,
						activation='tanh',
						return_sequences=False))
RNN_model.add(Dropout(0.2)) 
RNN_model.add(Dense(1, activation='sigmoid'))

# printing model summary
print(RNN_model.summary())

# Compiling model
RNN_model.compile(
	loss="binary_crossentropy",
	optimizer='adam',
	metrics=['accuracy']
)

@tf.function
def predict_fn(input_tensor):
    return RNN_model(input_tensor)

predictions = predict_fn(input_tensor)
print(predictions)

# Lấy giá trị dự đoán
values = predictions.numpy().flatten()

# Tạo DataFrame từ giá trị dự đoán
df_predictions = pd.DataFrame({'Model_name':'RNN','Value': values})

# Lưu vào file CSV
df_predictions.to_csv('C:/Users/hai/DuLieuKQTN/Prediction0505.csv', index=False)

Model: "SimpleRNN"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_23 (Embedding)    (None, 500, 32)           160000    
                                                                 
 simple_rnn_4 (SimpleRNN)    (None, 128)               20608     
                                                                 
 dropout_23 (Dropout)        (None, 128)               0         
                                                                 
 dense_23 (Dense)            (None, 1)                 129       
                                                                 
Total params: 180,737
Trainable params: 180,737
Non-trainable params: 0
_________________________________________________________________
None
tf.Tensor(
[[0.46059188]
 [0.4570467 ]
 [0.46609864]
 [0.46061403]
 [0.47009686]
 [0.47222224]
 [0.44586992]
 [0.46600774]
 [0.469097  ]
 [0.47146964]
 [0.4671556 ]
 [0.4760411 ]

In [37]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential

# Đọc dữ liệu từ file CSV
data = pd.read_csv('C:/Users/hai/hai_data_dxl/News050523_hai.csv')

# Tiền xử lý dữ liệu nếu cần
# ...

embd_len = 32
max_words = 500
vocab_size = 5000

# Chuyển đổi dữ liệu đầu vào thành một tensor hoặc đối tượng có cấu trúc tương tự
input_data = np.array(data['new_content'])

tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(input_data)

# Chuyển đổi văn bản thành chỉ số
sequences = tokenizer.texts_to_sequences(input_data)

# Đảm bảo độ dài cố định của mỗi mẫu
padded_sequences = pad_sequences(sequences, maxlen=max_words)

input_tensor = tf.convert_to_tensor(padded_sequences)

# Creating a RNN model
gru_model = Sequential(name="GRU")
gru_model.add(Embedding(vocab_size,
						embd_len,
						input_length=max_words))

# In case of a stacked(more than one layer of RNN)
# use return_sequences=True
gru_model.add(GRU(128,
						activation='tanh',
						return_sequences=False))
gru_model.add(Dropout(0.2)) 
gru_model.add(Dense(1, activation='sigmoid'))

# printing model summary
print(gru_model.summary())

# Compiling model
gru_model.compile(
	loss="binary_crossentropy",
	optimizer='adam',
	metrics=['accuracy']
)

@tf.function
def predict_fn(input_tensor):
    return gru_model(input_tensor)

predictions1 = predict_fn(input_tensor)
print(predictions1)

Model: "GRU"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_26 (Embedding)    (None, 500, 32)           160000    
                                                                 
 gru_7 (GRU)                 (None, 128)               62208     
                                                                 
 dropout_26 (Dropout)        (None, 128)               0         
                                                                 
 dense_26 (Dense)            (None, 1)                 129       
                                                                 
Total params: 222,337
Trainable params: 222,337
Non-trainable params: 0
_________________________________________________________________
None
tf.Tensor(
[[0.49550107]
 [0.49550107]
 [0.49550107]
 [0.49550107]
 [0.49550107]
 [0.49550107]
 [0.49550107]
 [0.49550107]
 [0.49550107]
 [0.49550107]
 [0.49550107]
 [0.49550107]], sha

In [38]:
# Lấy giá trị dự đoán
values = predictions1.numpy().flatten()

# Đọc dữ liệu cũ từ tệp CSV hoặc cơ sở dữ liệu
old_data = pd.read_csv('C:/Users/hai/DuLieuKQTN/Prediction0505.csv')

# Thêm dữ liệu mới vào DataFrame
new_data = pd.DataFrame({'Model_name':'GRU','Value': values})

# Ghi dữ liệu mới vào tệp CSV hoặc cơ sở dữ liệu
new_data.to_csv('C:/Users/hai/DuLieuKQTN/Prediction0505.csv', mode='a', header=False, index=False)

In [43]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential

# Đọc dữ liệu từ file CSV
data = pd.read_csv('C:/Users/hai/hai_data_dxl/News050523_hai.csv')

# Tiền xử lý dữ liệu nếu cần
# ...

embd_len = 32
max_words = 500
vocab_size = 5000

# Chuyển đổi dữ liệu đầu vào thành một tensor hoặc đối tượng có cấu trúc tương tự
input_data = np.array(data['new_content'])

tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(input_data)

# Chuyển đổi văn bản thành chỉ số
sequences = tokenizer.texts_to_sequences(input_data)

# Đảm bảo độ dài cố định của mỗi mẫu
padded_sequences = pad_sequences(sequences, maxlen=max_words)

input_tensor = tf.convert_to_tensor(padded_sequences)

# Creating a RNN model
lstm_model = Sequential(name="LSTM")
lstm_model.add(Embedding(vocab_size,
						embd_len,
						input_length=max_words))

# In case of a stacked(more than one layer of RNN)
# use return_sequences=True
lstm_model.add(LSTM(128,
						activation='tanh',
						return_sequences=False))
lstm_model.add(Dropout(0.2)) 
lstm_model.add(Dense(1, activation='sigmoid'))

# printing model summary
print(lstm_model.summary())

# Compiling model
lstm_model.compile(
    loss="binary_crossentropy",
    optimizer='adam',
    metrics=['accuracy']
)
# Thực hiện dự đoán
@tf.function
def predict_fn(input_tensor):
    return lstm_model(input_tensor)

predictions2 = predict_fn(input_tensor)
print(predictions2)

Model: "LSTM"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_31 (Embedding)    (None, 500, 32)           160000    
                                                                 
 lstm_18 (LSTM)              (None, 128)               82432     
                                                                 
 dropout_31 (Dropout)        (None, 128)               0         
                                                                 
 dense_31 (Dense)            (None, 1)                 129       
                                                                 
Total params: 242,561
Trainable params: 242,561
Non-trainable params: 0
_________________________________________________________________
None
tf.Tensor(
[[0.4981125]
 [0.4981125]
 [0.4981125]
 [0.4981125]
 [0.4981125]
 [0.4981125]
 [0.4981125]
 [0.4981125]
 [0.4981125]
 [0.4981125]
 [0.4981125]
 [0.4981125]], shape=(12, 1),

In [44]:
# Lấy giá trị dự đoán
values = predictions2.numpy().flatten()

# Đọc dữ liệu cũ từ tệp CSV hoặc cơ sở dữ liệu
old_data = pd.read_csv('C:/Users/hai/DuLieuKQTN/Prediction0505.csv')

# Thêm dữ liệu mới vào DataFrame
new_data = pd.DataFrame({'Model_name':'LSTM','Value': values})

# Ghi dữ liệu mới vào tệp CSV hoặc cơ sở dữ liệu
new_data.to_csv('C:/Users/hai/DuLieuKQTN/Prediction0505.csv', mode='a', header=False, index=False)

In [46]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential

# Đọc dữ liệu từ file CSV
data = pd.read_csv('C:/Users/hai/hai_data_dxl/News050523_hai.csv')

# Tiền xử lý dữ liệu nếu cần
# ...

embd_len = 32
max_words = 500
vocab_size = 5000

# Chuyển đổi dữ liệu đầu vào thành một tensor hoặc đối tượng có cấu trúc tương tự
input_data = np.array(data['new_content'])

tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(input_data)

# Chuyển đổi văn bản thành chỉ số
sequences = tokenizer.texts_to_sequences(input_data)

# Đảm bảo độ dài cố định của mỗi mẫu
padded_sequences = pad_sequences(sequences, maxlen=max_words)

input_tensor = tf.convert_to_tensor(padded_sequences)

# Creating a Bi-LSTM model
bi_lstm_model = Sequential(name="Bi-LSTM")
bi_lstm_model.add(Embedding(vocab_size,
						embd_len,
						input_length=max_words))

# In case of a stacked(more than one layer of RNN)
# use return_sequences=True
bi_lstm_model.add(Bidirectional(LSTM(128,
						activation='tanh',
						return_sequences=False)))
bi_lstm_model.add(Dropout(0.2)) 
bi_lstm_model.add(Dense(1, activation='sigmoid'))

# printing model summary
print(bi_lstm_model.summary())

# Compiling model
bi_lstm_model.compile(
	loss="binary_crossentropy",
	optimizer='adam',
	metrics=['accuracy']
)
# Thực hiện dự đoán
@tf.function
def predict_fn(input_tensor):
    return bi_lstm_model(input_tensor)

predictions3 = predict_fn(input_tensor)
print(predictions3)

Model: "Bi-LSTM"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_33 (Embedding)    (None, 500, 32)           160000    
                                                                 
 bidirectional_11 (Bidirecti  (None, 256)              164864    
 onal)                                                           
                                                                 
 dropout_33 (Dropout)        (None, 256)               0         
                                                                 
 dense_33 (Dense)            (None, 1)                 257       
                                                                 
Total params: 325,121
Trainable params: 325,121
Non-trainable params: 0
_________________________________________________________________
None
tf.Tensor(
[[0.4979275 ]
 [0.49963146]
 [0.49847096]
 [0.49836588]
 [0.4974691 ]
 [0.49939904]
 [0.49766377]
 [0.4

In [47]:
# Lấy giá trị dự đoán
values = predictions3.numpy().flatten()

# Đọc dữ liệu cũ từ tệp CSV hoặc cơ sở dữ liệu
old_data = pd.read_csv('C:/Users/hai/DuLieuKQTN/Prediction0505.csv')

# Thêm dữ liệu mới vào DataFrame
new_data = pd.DataFrame({'Model_name':'BiLSTM','Value': values})

# Ghi dữ liệu mới vào tệp CSV hoặc cơ sở dữ liệu
new_data.to_csv('C:/Users/hai/DuLieuKQTN/Prediction0505.csv', mode='a', header=False, index=False)

In [48]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential

# Đọc dữ liệu từ file CSV
data = pd.read_csv('C:/Users/hai/hai_data_dxl/News050523_hai.csv')

# Tiền xử lý dữ liệu nếu cần
# ...

embd_len = 32
max_words = 500
vocab_size = 5000

# Chuyển đổi dữ liệu đầu vào thành một tensor hoặc đối tượng có cấu trúc tương tự
input_data = np.array(data['new_content'])

tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(input_data)

# Chuyển đổi văn bản thành chỉ số
sequences = tokenizer.texts_to_sequences(input_data)

# Đảm bảo độ dài cố định của mỗi mẫu
padded_sequences = pad_sequences(sequences, maxlen=max_words)

input_tensor = tf.convert_to_tensor(padded_sequences)

# Creating a RNN model
bi_gru_model = Sequential(name="Bi-GRU")
bi_gru_model.add(Embedding(vocab_size,
						embd_len,
						input_length=max_words))

# In case of a stacked(more than one layer of RNN)
# use return_sequences=True
bi_gru_model.add(Bidirectional(GRU(128,
						activation='tanh',
						return_sequences=False)))
bi_gru_model.add(Dropout(0.2)) 
bi_gru_model.add(Dense(1, activation='sigmoid'))

# printing model summary
print(bi_gru_model.summary())

# Compiling model
bi_gru_model.compile(
	loss="binary_crossentropy",
	optimizer='adam',
	metrics=['accuracy']
)
# Thực hiện dự đoán
@tf.function
def predict_fn(input_tensor):
    return bi_gru_model(input_tensor)

predictions4 = predict_fn(input_tensor)
print(predictions4)

Model: "Bi-GRU"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_34 (Embedding)    (None, 500, 32)           160000    
                                                                 
 bidirectional_12 (Bidirecti  (None, 256)              124416    
 onal)                                                           
                                                                 
 dropout_34 (Dropout)        (None, 256)               0         
                                                                 
 dense_34 (Dense)            (None, 1)                 257       
                                                                 
Total params: 284,673
Trainable params: 284,673
Non-trainable params: 0
_________________________________________________________________
None
tf.Tensor(
[[0.49487156]
 [0.49568006]
 [0.49162993]
 [0.49088183]
 [0.4953909 ]
 [0.49479347]
 [0.49541613]
 [0.49

In [49]:
# Lấy giá trị dự đoán
values = predictions4.numpy().flatten()

# Đọc dữ liệu cũ từ tệp CSV hoặc cơ sở dữ liệu
old_data = pd.read_csv('C:/Users/hai/DuLieuKQTN/Prediction0505.csv')

# Thêm dữ liệu mới vào DataFrame
new_data = pd.DataFrame({'Model_name':'BGRU','Value': values})

# Ghi dữ liệu mới vào tệp CSV hoặc cơ sở dữ liệu
new_data.to_csv('C:/Users/hai/DuLieuKQTN/Prediction0505.csv', mode='a', header=False, index=False)